### ISSUE TITLE
Build errors when building template example

### ISSUE THREAD

**Issue by Kohlrabi** [christopherpoole/CADMesh#13]
I get the following build error when building the template example, after installing CADMesh:

```
[ 20%] Building CXX object CMakeFiles/cadmesh_template.dir/src/DetectorConstruction.cc.o
/data/et119/terasa/git/geant4/CADMesh/examples/template/src/DetectorConstruction.cc: In member function ‘virtual G4VPhysicalVolume* DetectorConstruction::Construct()’:
/data/et119/terasa/git/geant4/CADMesh/examples/template/src/DetectorConstruction.cc:49:54: error: incomplete type ‘G4VisAttributes’ used in nested name specifier
     world_logical->SetVisAttributes(G4VisAttributes::Invisible);
                                                      ^~~~~~~~~
/data/et119/terasa/git/geant4/CADMesh/examples/template/src/DetectorConstruction.cc:52:13: error: expected primary-expression before ‘*’ token
     CADMesh * mesh = new CADMesh((char*) "det.stl");
             ^
/data/et119/terasa/git/geant4/CADMesh/examples/template/src/DetectorConstruction.cc:52:15: error: ‘mesh’ was not declared in this scope
     CADMesh * mesh = new CADMesh((char*) "det.stl");
               ^~~~
/data/et119/terasa/git/geant4/CADMesh/examples/template/src/DetectorConstruction.cc:52:15: note: suggested alternative: ‘cosh’
     CADMesh * mesh = new CADMesh((char*) "det.stl");
               ^~~~
               cosh
/data/et119/terasa/git/geant4/CADMesh/examples/template/src/DetectorConstruction.cc:52:26: error: expected type-specifier before ‘CADMesh’
     CADMesh * mesh = new CADMesh((char*) "det.stl");
```

The first error is probably caused by restructuring of the GEANT4 version I link against (10.4), and can be fixed by `#include "G4VisAttributes.hh".` (though the developers warn that usage of `::Invisible` is deprecated and should be replaced by a call to `::GetInvisible()`)

From my understanding of the codebase the other errors are caused by the absence of a CADMesh constructor in the code. Shouldn't this code call the TessellatedMesh constructor explicitely? I managed to fix it by calling the `CADMesh::TessellatedMesh` constructor instead, but I do not know if that is the way it is intended to work. If yes, I can prepare a PR.

**Comment by christopherpoole** [comment]
Is this on the master branch? If so, I am making updates in preparation for version 2, and I havne't yet updated the template example I don't think.

In the mean time, v1.1 is the current release version, and can be found here:

    https://github.com/christopherpoole/CADMesh/releases/tag/v1.1
    https://github.com/christopherpoole/CADMesh/tree/v1.1

**Comment by christopherpoole** [comment]
Just updated the template example to reflect the ongoing changes to the API. See [here](https://github.com/christopherpoole/CADMesh/blob/665ff1e7d24f0efe1addb67da0121ef5c36a474d/examples/template/src/DetectorConstruction.cc#L55).

**Comment by Kohlrabi** [comment]
Great. I was looking at this example to implement the recent changes in my g4py interface to CADMesh, but I should probably wait until v2 is final.
