### ISSUE TITLE
Does the tetgen AGPL license propogate to CADMesh?

### ISSUE THREAD

**Issue by christopherpoole** [christopherpoole/CADMesh#17]

**Comment by Supernabla** [comment]
I would say "yes". Otherwise, anyone could write a wrapper library around gpl code to get rid of the gpl copyleft.

**Comment by christopherpoole** [comment]
CADMesh 2 is now distributed has a header only, where tetgen is totally optional. I could also distribute a header without the tetgen code in there at all.

I can reopen this if it become a problem...
