### ISSUE TITLE
cannot find -lcadmesh

### ISSUE THREAD

**Issue by deanrusby** [christopherpoole/CADMesh#26]
Hi again everyone.

So I was installing CADMesh onto a cluster after it working seamlessly for month on my own work station. I followed the same procedure I did last time but I get this error at the end of the make process. 

> Scanning dependencies of target cadmesh_example
> [ 20%] Building CXX object CMakeFiles/cadmesh_example.dir/cadmesh_example.cc.o
> [ 40%] Building CXX object CMakeFiles/cadmesh_example.dir/src/DetectorConstruction.cc.o
> [ 60%] Building CXX object CMakeFiles/cadmesh_example.dir/src/PhysicsList.cc.o
> [ 80%] Building CXX object CMakeFiles/cadmesh_example.dir/src/PrimaryGeneratorAction.cc.o
> [100%] Linking CXX executable cadmesh_example
> /usr/tce/packages/binutils/binutils-2.30/bin/ld: cannot find -lcadmesh
> collect2: error: ld returned 1 exit status
> make[2]: *** [cadmesh_example] Error 1
> make[1]: *** [CMakeFiles/cadmesh_example.dir/all] Error 2
> make: *** [all] Error 2

What have I missed?

**Comment by christopherpoole** [comment]
Pleae3 try version 2, there is no longer a need to compile CADMesh yourself.
