### ISSUE TITLE
Issue installing CADmesh v1.1 on MAC HighSierra 10.13.6

### ISSUE THREAD

**Issue by PietroGiampa** [christopherpoole/CADMesh#27]
Hi Guys,

I have been trying to install CADmesh on my computer by simply following the instructions but when I do make the first time the installation crashes with a fatal error.

---------------------------------------------------++
Here are the steps I took, following the standard instructions:
**1) git clone https://github.com/christopherpoole/CADMesh.git
2) cd CADmesh
3) git checkout -b v1.1
4) mkdir build; cd build
5) cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/Users/giampapietro/Documents/Software/lolxsim/build
6) make**

---------------------------------------------------++
First off I get the following message when I do step 5:
**CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.**

  **MACOSX_RPATH is not specified for the following targets:**

   **cadmesh**

**This warning is for project developers.  Use -Wno-dev to suppress it.
-- Generating done
-- Build files have been written to: /Users/giampapietro/Documents/Software/lolxsim/CADMesh/build**

---------------------------------------------------++
Here the error message I get when I run make:
**/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:3656:5: warning: destructor called on non-final
      'CADMesh::File::BuiltInReader' that has virtual functions but non-virtual destructor
      [-Wdelete-non-virtual-dtor]
    __data_.second().~_Tp();**
    ^
**/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:3612:5: note: in instantiation of member function
      'std::__1::__shared_ptr_emplace<CADMesh::File::BuiltInReader,
      std::__1::allocator<CADMesh::File::BuiltInReader> >::__on_zero_shared' requested here
    __shared_ptr_emplace(_Alloc __a)**
    ^
**/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:4277:26: note: in instantiation of member function
      'std::__1::__shared_ptr_emplace<CADMesh::File::BuiltInReader,
      std::__1::allocator<CADMesh::File::BuiltInReader> >::__shared_ptr_emplace' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);**
                         ^
**/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:4656:29: note: in instantiation of function template
      specialization 'std::__1::shared_ptr<CADMesh::File::BuiltInReader>::make_shared<>' requested here
    return shared_ptr<_Tp>::make_shared(_VSTD::forward<_Args>(__args)...);**
                            ^
**/Users/giampapietro/Documents/Software/lolxsim/CADMesh/src/BuiltInReader.cc:43:17: note: in instantiation of
      function template specialization 'std::__1::make_shared<CADMesh::File::BuiltInReader>' requested here
    return std::make_shared<BuiltInReader>();**
                ^
**/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:3656:23: note: qualify call to silence this warning
    __data_.second().~_Tp();
                      ^
1 warning and 7 errors generated.
make[2]: *** [CMakeFiles/cadmesh.dir/src/BuiltInReader.cc.o] Error 1
make[1]: *** [CMakeFiles/cadmesh.dir/all] Error 2
make: *** [all] Error 2**

---------------------------------------------------++
Any help would be greatly appreciated. Thanks guys.

**Comment by padsley** [comment]
I'm not a Mac user but I know someone who is and uses Cadmesh so I'll ask
if he's got any ideas.

Philip Adsley

**Comment by christopherpoole** [comment]
Please try version 2. It is header only, requires no complication, and has no dependencies for PLY, OBJ, and STL file formats.
