### ISSUE TITLE
Library file locations

### ISSUE THREAD

**Issue by padsley** [christopherpoole/CADMesh#28]
I don't expect to get a reply to this because there seems to be no support for CADMesh but I wanted to raise it as an issue:

CADMesh for some reason decide to put `libcadmesh.so` in a different directory from the other library files that it uses (`libassimp.so` and `libtet.so`). I don't know if this is deliberate but it seems odd. Is there an error somewhere in CMake?

I note, again, that the instructions for installing CADMesh don't seem to work on many systems.

**Comment by christopherpoole** [comment]
Please try the latest version. Version 2. There is no longer a requirement for assimp and tegen if you are only interested in loading OBJ, STL or PLY files.
