### ISSUE TITLE
Optional dependencies

### ISSUE THREAD

**Issue by kohlrabi** [christopherpoole/CADMesh#32]
ASSIMP and TETGEN are mentioned as optional dependencies, but what is the advantage of using either or both compared to the built-in loaders? I asked the same on the GEANT4 forums. Maybe just add a sentence or two to the README.

**Comment by christopherpoole** [comment]
Sorry, I missed your post on the forum. 

The main advantage is not having to install the dependencies. I looked at the emails I was receiving over the years, and there were a lot relating to not wanting or being able to install dependencies in HPC environments in particular, or for some other reason in general.

I was also receiving a lot of emails about the installation process itself. Which lead to a header only distribution, and ultimately the view that the dependencies were causing a problem there as well.

So, now they are optional.

I will add something to this effect in the readme. Thanks for your input.
