### ISSUE TITLE
Multiple definition when include CADMesh.hh in different .cc file in one project

### ISSUE THREAD

**Issue by zhaoha** [christopherpoole/CADMesh#33]
Hi, I have a problem when using CADMesh. I construct my GEANT4 geometry in different header file and then assemble them together in MyDetectorConstruction.cc. So I include CADMesh.hh in every header of these sub parts. When I compile my project, it reports error like in the picture.
![65d942c3-c90c-4f73-8099-9118e173bc3d](https://user-images.githubusercontent.com/7592082/85944391-eea8d200-b968-11ea-804e-59517c131958.jpg)

Please check it out. Thank you!

**Comment by christopherpoole** [comment]
Thanks for reporting this. It is being fixed now.

**Comment by christopherpoole** [comment]
@zhaoha The latest release should fix this problem for you now.

**Comment by zhaoha** [comment]
Thanks. It works😀
