### ISSUE TITLE
Problem in RunAction, EventAction, SteppingAction.

### ISSUE THREAD

**Issue by tanjil08** [christopherpoole/CADMesh#6]
The model runs without the use of RunAction, EventAction, SteppingAction. But after the initialization of the user action classes, I get the following error: 

![16 11-36511-screenshot_1](https://cloud.githubusercontent.com/assets/14133639/10808238/3fb2865e-7da6-11e5-92f7-0bf9f4cb82f2.jpg)

Any ideas on how to fix this? Thanks in advance.

**Comment by stevenwalton** [comment]
Do you have the GEANT4 libraries linked?
