### ISSUE TITLE
Problem with daughter volumes

### ISSUE THREAD

**Issue by jharms24** [christopherpoole/CADMesh#9]
Hello,

I am importing a CAD model of a shipping container and placing several objects inside of it. In order to track the pathlength through the various objects inside the container, I have implemented a stepping action class. However, it seems that the particles I am sending through the container volume can only see the container and none of the daughter objects inside of it (i.e. touchable->GetVolume()->GetCopyNo() always returns the copy number of the container).

Have you seen any issues like this before or do you know of a way to access the copy number of daughter volumes?

Thanks,
Joe

**Comment by christopherpoole** [comment]
Hi Joe,

Is the mother volume (the shipping container) a shell? If so, the daughter volumes won't be logical daughters -they are inside the container, but not logically within it. Try and set the mother volume of the daughters to the same mother volume as the container.

Chris.

**Comment by jharms24** [comment]
It seems like that was the problem. Everything works as long as they all have the same mother.

Thanks,
Joe
